-- CueVex mobile push notification production tables.
-- Run this in Supabase SQL Editor before deploying push notification events.

create table if not exists public.user_notification_settings (
  user_id bigint primary key references public.mobile_users(id) on delete cascade,
  push_enabled boolean not null default true,
  post_likes_enabled boolean not null default true,
  post_comments_enabled boolean not null default true,
  comment_replies_enabled boolean not null default true,
  comment_likes_enabled boolean not null default true,
  new_followers_enabled boolean not null default true,
  mutual_follows_enabled boolean not null default true,
  account_security_enabled boolean not null default true,
  login_changes_enabled boolean not null default true,
  service_announcements_enabled boolean not null default true,
  show_preview_enabled boolean not null default true,
  type_only_enabled boolean not null default false,
  quiet_hours_enabled boolean not null default false,
  updated_at timestamptz not null default now()
);

create or replace function public.set_user_notification_settings_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_user_notification_settings_updated_at on public.user_notification_settings;

create trigger trg_user_notification_settings_updated_at
before update on public.user_notification_settings
for each row
execute function public.set_user_notification_settings_updated_at();

create table if not exists public.user_push_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.mobile_users(id) on delete cascade,
  expo_push_token text not null,
  device text not null default '',
  platform text not null default '',
  is_active boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(user_id, expo_push_token)
);

create index if not exists idx_user_push_tokens_user
on public.user_push_tokens(user_id);

create index if not exists idx_user_push_tokens_active
on public.user_push_tokens(is_active, last_seen_at desc);

create table if not exists public.user_notification_events (
  id bigint generated by default as identity primary key,
  recipient_user_id bigint not null references public.mobile_users(id) on delete cascade,
  actor_user_id bigint not null references public.mobile_users(id) on delete cascade,
  event_type text not null,
  source_type text not null,
  source_id bigint not null,
  title text not null default '',
  body text not null default '',
  status text not null default 'pending',
  error text not null default '',
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  check (status in ('pending', 'sent', 'failed', 'skipped'))
);

alter table public.user_notification_events
add column if not exists expo_ticket_ids jsonb not null default '[]'::jsonb;

alter table public.user_notification_events
add column if not exists expo_receipts jsonb not null default '{}'::jsonb;

alter table public.user_notification_events
add column if not exists receipt_checked_at timestamptz;

create index if not exists idx_user_notification_events_recipient_created
on public.user_notification_events(recipient_user_id, created_at desc);

create index if not exists idx_user_notification_events_status_created
on public.user_notification_events(status, created_at desc);

create index if not exists idx_user_notification_events_source
on public.user_notification_events(event_type, source_type, source_id, recipient_user_id);
