create table if not exists public.friend_match_invites (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  host_player text not null,
  game_type text not null default 'nine_ball',
  target_rounds integer not null default 5,
  shot_time_limit integer not null default 0,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'expired')),
  guest_user_id bigint references public.mobile_users(id) on delete set null,
  guest_player text,
  created_at bigint not null,
  expires_at bigint not null,
  accepted_at bigint
);

alter table public.friend_match_invites enable row level security;

create index if not exists idx_friend_match_invites_token_hash
  on public.friend_match_invites(token_hash);

create index if not exists idx_friend_match_invites_status_expires
  on public.friend_match_invites(status, expires_at);
