-- CueVex analytics schema for Supabase Postgres.
-- Run this full script in Supabase SQL Editor.
--
-- Safety model:
-- 1. Create timestamped backup tables in cuevex_backups and commit them first.
-- 2. Apply analytics schema changes in a separate transaction.
-- 3. Avoid destructive operations; this script does not drop or delete data.

begin;

create schema if not exists cuevex_backups;

do $$
declare
  backup_suffix text := to_char(clock_timestamp(), 'YYYYMMDD_HH24MISS');
  source_table text;
  backup_table text;
  tables_to_backup text[] := array[
    'mobile_users',
    'analytics_recordings',
    'analytics_events',
    'analytics_shot_events',
    'analytics_practice_stats',
    'analytics_sync_state'
  ];
begin
  foreach source_table in array tables_to_backup loop
    if to_regclass(format('public.%I', source_table)) is not null then
      backup_table := format('%I.%I', 'cuevex_backups', source_table || '_before_analytics_' || backup_suffix);
      execute format('create table %s as table public.%I', backup_table, source_table);
      raise notice 'Backed up public.% to %', source_table, backup_table;
    else
      raise notice 'Skip backup: public.% does not exist yet', source_table;
    end if;
  end loop;
end $$;

commit;

begin;

create extension if not exists pgcrypto;

alter table public.mobile_users
add column if not exists user_uuid uuid not null default gen_random_uuid();

create unique index if not exists idx_mobile_users_user_uuid
on public.mobile_users(user_uuid);

create table if not exists public.analytics_recordings (
  game_id text primary key,
  owner_user_uuid uuid references public.mobile_users(user_uuid) on delete set null,
  game_type text not null,
  start_time timestamptz not null,
  end_time timestamptz,
  duration_seconds double precision,
  player1_name text,
  player2_name text,
  winner text,
  player1_score integer not null default 0,
  player2_score integer not null default 0,
  target_rounds integer not null default 0,
  video_path text not null default '',
  video_resolution text,
  video_fps integer,
  file_size_mb double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_analytics_recordings_start_time
on public.analytics_recordings(start_time desc);

create index if not exists idx_analytics_recordings_game_type_start
on public.analytics_recordings(game_type, start_time desc);

create index if not exists idx_analytics_recordings_player1
on public.analytics_recordings(player1_name);

create index if not exists idx_analytics_recordings_player2
on public.analytics_recordings(player2_name);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  game_id text not null references public.analytics_recordings(game_id) on delete cascade,
  event_time double precision not null,
  event_type text not null,
  data jsonb not null default '{}'::jsonb,
  target_ball integer,
  potted_ball integer,
  first_contact integer,
  created_at timestamptz not null default now()
);

create index if not exists idx_analytics_events_game_time
on public.analytics_events(game_id, event_time asc);

create index if not exists idx_analytics_events_type
on public.analytics_events(event_type);

create table if not exists public.analytics_shot_events (
  id bigint generated by default as identity primary key,
  game_id text references public.analytics_recordings(game_id) on delete set null,
  player_user_uuid uuid references public.mobile_users(user_uuid) on delete set null,
  player_name text,
  shot_index integer not null default 0,
  created_at timestamptz not null default now(),
  mode text,
  target_ball integer,
  first_contact integer,
  potted_balls jsonb not null default '[]'::jsonb,
  pocket_result text not null default 'missed',
  cue_ball_potted boolean not null default false,
  is_foul boolean not null default false,
  foul_reason text,
  impact_angle double precision,
  ideal_angle double precision,
  thickness_result text not null default 'unknown',
  distance_bucket text not null default 'unknown',
  difficulty_level text not null default 'unknown',
  success_prob double precision,
  position_success_prob double precision,
  planned_cue_landing jsonb,
  actual_cue_landing jsonb,
  cue_landing_error_px double precision,
  next_ball_quality text,
  raw_event_json jsonb not null default '{}'::jsonb
);

create unique index if not exists idx_analytics_shot_events_unique_game_shot
on public.analytics_shot_events(game_id, shot_index);

create index if not exists idx_analytics_shot_events_player_created
on public.analytics_shot_events(player_name, created_at asc);

create table if not exists public.analytics_practice_stats (
  id bigint generated by default as identity primary key,
  game_id text not null references public.analytics_recordings(game_id) on delete cascade,
  practice_type text not null,
  pattern text,
  total_attempts integer not null default 0,
  successful_attempts integer not null default 0,
  success_rate double precision,
  avg_shot_time double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(game_id, practice_type, pattern)
);

create index if not exists idx_analytics_practice_stats_type
on public.analytics_practice_stats(practice_type);

create table if not exists public.analytics_sync_state (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_key text not null,
  source text not null default 'sqlite',
  sync_status text not null default 'pending',
  last_synced_at timestamptz,
  error_message text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(entity_type, entity_key, source)
);

create index if not exists idx_analytics_sync_state_status
on public.analytics_sync_state(sync_status, updated_at desc);

commit;

-- Optional verification after the transaction completes:
--
-- select table_schema, table_name
-- from information_schema.tables
-- where (
--     table_schema = 'public'
--     and table_name in (
--       'analytics_recordings',
--       'analytics_events',
--       'analytics_shot_events',
--       'analytics_practice_stats',
--       'analytics_sync_state'
--     )
--   )
--   or (
--     table_schema = 'cuevex_backups'
--     and table_name like '%_before_analytics_%'
--   )
-- order by table_schema, table_name;
--
-- select column_name, data_type, is_nullable
-- from information_schema.columns
-- where table_schema = 'public'
--   and table_name = 'mobile_users'
--   and column_name = 'user_uuid';
